ARTS-622 ARTS-620 - Adding create-site, create-person permissions
NDPH-ARTS/mts-trial-deployment-config pull request #101
Opened 2021-03-23 18:42 UTC by shajidissa

ARTS-622 - create-site permissions
ARTS-620 - create-person permissions

## Description
Creating permissions

### Changes
- [ARTS-620] [ARTS-622]- permissions

### Checklist:

- [ ] Branch name follows convention (feature/arts-###-short-name OR fix/arts-###-short-name)
- [ ] I have included a short-meaningful title, description and changes for this PR

2021-03-23 18:50 UTC, sameendph submitted a review, later dismissed
looks correct. Approving

2021-03-23 19:11 UTC, darrengsmithson requested changes
think create-person has been added by mistake - if this is for 620 and 622 the change should be 
- id: create-site
- id: link-user

2021-03-24 08:54 UTC, sameendph approved these changes
approving

2021-03-24 08:55 UTC, darrengsmithson approved these changes

2021-03-24 09:51 UTC, ben0deinde approved these changes

2021-03-25 08:54 UTC, merged