Deploy/arts 729 correct authentication
NDPH-ARTS/mts-trial-deployment-config pull request #115
Opened 2021-04-06 12:51 UTC by LizaShak

## Description
Correct the authentication flow

### Changes
[ARTS-729] - the following changes were applied:
- Use separate client applications for backend and ui
- Use predefined scopes
- Init service uses a managed identity in Azure, or client application in CI to require token. 
- Init service managed identity/client application is assigned with internal services application role and it is used to authorise it.

### Checklist:

- [ ] Branch name follows convention (feature/arts-###-short-name OR fix/arts-###-short-name)
- [ ] I have included a short-meaningful title, description and changes for this PR

2021-04-06 13:05 UTC, tamirkamara requested changes

2021-04-06 13:05 UTC, tamirkamara commented on .github/workflows/terraform-plan-apply.yml
> +          sp_object_id=$(az ad sp list --display-name $init_service_name --query "[0] .objectId")
I see that Terraform exports the "principal_id" of the identity created. Isn't that the same as the one you're using here?

2021-04-06 14:48 UTC, tamirkamara submitted a review, later dismissed

2021-04-06 15:08 UTC, mdp0 approved these changes, later dismissed

2021-04-07 10:48 UTC, mdp0 approved these changes

2021-04-07 11:09 UTC, eladiw approved these changes

2021-04-07 11:10 UTC, merged