Adding PR templates
NDPH-ARTS/mts-trial-deployment-config pull request #14
Opened 2021-01-14 18:07 UTC by eladiw

Adding a template for future PRs

2021-01-17 07:47 UTC, anatbal approved these changes, later dismissed
Looks good

2021-01-18 06:52 UTC, tamirkamara requested changes
Please check the template in the mts-services repo and do something similar here

2021-01-18 10:31 UTC, anatbal submitted a review, later dismissed

2021-01-21 18:30 UTC, tamirkamara approved these changes

2021-01-21 19:27 UTC, shajidissa approved these changes

2021-01-21 21:14 UTC, merged