TF templates updates
NDPH-ARTS/mts-trial-deployment-config pull request #2
Opened 2020-12-28 19:15 UTC by eladiw

Adding
Audit store
Fhir server
Readme file

bug fix for the CI workflow

2020-12-29 10:53 UTC, shajidissa commented on sample_trial/definition.json
> +    "site_image_tag": "latest",
So all microservices will be listed here with docker images and tags, awesome

2020-12-29 10:54 UTC, shajidissa commented on sample_trial/definition.json
>      "rootUser": "jondoe@contoso.com",
Is this an AD user ? configured manually ?

2020-12-29 10:56 UTC, shajidissa reviewed
looks good

2020-12-29 12:00 UTC, eladiw commented on sample_trial/definition.json
>      "rootUser": "jondoe@contoso.com",
in AD, yes

2020-12-29 13:18 UTC, shajidissa commented on terraform/main.tf
> +  config_server_image_name = var.config_server_image_name
what's the config_server ?

2020-12-29 13:40 UTC, shajidissa reviewed
cool

2020-12-29 14:15 UTC, tamirkamara requested changes

2020-12-29 14:15 UTC, tamirkamara commented on terraform/trial_rg/modules/fhir/main.tf
> +  name                = "fhir-app-service"
This will conflict with every trial, I guess it should follow the same pattern as the services

2020-12-29 14:15 UTC, tamirkamara commented on terraform/trial_rg/modules/fhir/main.tf
> +    linux_fx_version = "DOCKER|mcr.microsoft.com/healthcareapis/r4-fhir-server:latest"
Should we allow to override the fhir image and/or tag?

2020-12-29 14:15 UTC, tamirkamara commented on terraform/trial_rg/modules/audit/main.tf
> +resource "azurerm_storage_account" "trial_audit" {
I think we should remove the audit resources since we don't know what it will be yet.

2020-12-29 14:15 UTC, tamirkamara commented on terraform/trial_rg/main.tf
> +  tenant_id           = "99804659-431f-48fa-84c1-65c9609de05b"
why do you need to provide tenant_id in all appservice instances?

2020-12-29 14:15 UTC, tamirkamara commented on terraform/trial_rg/modules/appservice/main.tf
>  # App service (web app)
Perhaps it's just me, but maybe appservice is a confusing term in our context. From the MTS perspective, this is a just service application, right? I think we can hide the azure implementation...

2020-12-29 14:15 UTC, tamirkamara commented on README.md
> +Copy the sample_trial directory into a new directory with a meaningful name. (e.g. trial987drugX) (Name cannot be longer than 19 characters).
I couldn't comment below on the var, but if you can add advanced validation on input variable.
https://www.terraform.io/docs/configuration/variables.html#custom-validation-rules

2020-12-29 14:15 UTC, tamirkamara commented on .github/workflows/terraform-plan-apply.yml
> +            JSONline="$JSONline },"
You should explain this block

2020-12-29 14:15 UTC, tamirkamara commented on terraform/trial_rg/modules/fhir/main.tf
> +resource "azurerm_app_service" "fhir_server" {
Have you confirmed that this works?
I don't see its database or anything that will configure it (like: how does it access the db)

2020-12-29 16:09 UTC, eladiw commented on terraform/main.tf
> +  config_server_image_name = var.config_server_image_name
not sure needed. its the image you supplied earlier today

2020-12-29 16:11 UTC, eladiw commented on terraform/trial_rg/modules/audit/main.tf
> +resource "azurerm_storage_account" "trial_audit" {
ok

2020-12-29 16:12 UTC, eladiw commented on terraform/trial_rg/main.tf
> +  tenant_id           = "99804659-431f-48fa-84c1-65c9609de05b"
redundant

2020-12-29 16:13 UTC, eladiw commented on terraform/trial_rg/modules/appservice/main.tf
>  # App service (web app)
web app?

2020-12-29 16:13 UTC, eladiw commented on terraform/trial_rg/modules/fhir/main.tf
> +resource "azurerm_app_service" "fhir_server" {
just deployed. haven't verified it yet. nor any other app service

2020-12-29 16:31 UTC, eladiw commented on terraform/trial_rg/modules/appservice/main.tf
>  # App service (web app)
Service Application?

2020-12-29 20:50 UTC, shajidissa commented on terraform/main.tf
> +  config_server_image_name = var.config_server_image_name
I still think this is necessary.. the json feeds into the trial-config-service, maybe another chat with Tamir and Mark needed.

2020-12-30 07:00 UTC, eladiw commented on terraform/trial_rg/modules/fhir/main.tf
> +resource "azurerm_app_service" "fhir_server" {
my latest commit made sure fhir is up and running and serving requests...

2020-12-30 08:19 UTC, tamirkamara approved these changes

2020-12-30 09:25 UTC, eladiw commented on terraform/main.tf
> +  config_server_image_name = var.config_server_image_name
this is the trial service config. lets talk later with tamir about this

2020-12-30 10:58 UTC, shajidissa approved these changes
All good

2020-12-30 12:26 UTC, merged