Test
NDPH-ARTS/mts-trial-deployment-config pull request #22
Opened 2021-01-17 13:24 UTC by eladiw

2021-01-17 20:26 UTC, mdp0 submitted a review, later dismissed

2021-01-18 07:46 UTC, tamirkamara requested changes

2021-01-18 07:46 UTC, tamirkamara commented on .github/workflows/terraform-plan-apply.yml
> +          issuer="https://login.microsoftonline.com/5d23383f-2acb-448e-8353-4b4573b82276/v2.0"
I think we should add a tenantId to the config json and get this from there.

2021-01-18 07:46 UTC, tamirkamara commented on .github/workflows/terraform-plan-apply.yml
> +          sed -i 's/\$\{\{clientId\}\}"/$ARM_CLIENT_ID/' ui_component/index.html
I don't think this is right - the clientId used by the UI isn't the same one as the terraform. You should also add this to the config json.

2021-01-18 07:46 UTC, tamirkamara commented on .github/workflows/terraform-plan-apply.yml
> +          sed -i 's/{{clientId}}"/$ARM_CLIENT_ID/' ui_component/index.html
This should be different than the one terraform uses... probably get this also from the config json.

2021-01-18 07:47 UTC, tamirkamara commented
@eladiw can you rename this branch to confirm to our standard?

2021-01-18 09:09 UTC, closed without merging