[ARTS 469] - use latest tag and correct images names
NDPH-ARTS/mts-trial-deployment-config pull request #27
Opened 2021-01-25 07:13 UTC by eladiw

## Description
Using correct images names (instead of placeholders) + changing to 'latest' which is now available

### Checklist:

- [X] Branch name follows convention (feature/arts-###-short-name OR fix/arts-###-short-name)
- [X] I have included a short-meaningful title, description and changes for this PR

2021-01-25 07:29 UTC, tamirkamara requested changes
FYI, this will fail until we start publishing latest images from the mts-services repo.

2021-01-25 07:29 UTC, tamirkamara commented on sample_trial/definition.json
> +        "image_name": "ghcr.io/ndph-arts/trial-practitioner-service",
```suggestion
        "image_name": "ghcr.io/ndph-arts/practitioner-service",
```

2021-01-25 07:29 UTC, tamirkamara commented on sample_trial/definition.json
> +        "image_name": "ghcr.io/ndph-arts/trial-site-service",
```suggestion
        "image_name": "ghcr.io/ndph-arts/site-service",
```

2021-01-25 07:44 UTC, tamirkamara commented on .github/workflows/validate.yml
> +    branches: [ main, feature/**, fix/** ]
btw, I think this can be on all branches...

2021-01-25 07:45 UTC, anatbal approved these changes, later dismissed

2021-01-25 07:49 UTC, eladiw commented on sample_trial/definition.json
> +        "image_name": "ghcr.io/ndph-arts/trial-role-service",
```suggestion
        "image_name": "ghcr.io/ndph-arts/role-service",
```

2021-01-25 07:52 UTC, eladiw commented on .github/workflows/terraform-plan-apply-shared-rg.yml
> +    branches: [ main, feature/**, fix/** ]
```suggestion
    branches: [ ** ]
```

2021-01-25 07:53 UTC, eladiw commented on .github/workflows/terraform-plan-apply.yml
> +    branches: [ main, feature/**, fix/** ]
```suggestion
    branches: [ ** ]
```

2021-01-25 07:54 UTC, eladiw commented on .github/workflows/validate.yml
> +    branches: [ main, feature/**, fix/** ]
```suggestion
    branches: [ ** ]
```

2021-01-25 12:43 UTC, anatbal approved these changes, later dismissed

2021-01-25 12:57 UTC, tamirkamara commented on .github/workflows/terraform-plan-apply-shared-rg.yml
> +    branches: [ '**' ]
You can delete this line since it's "all"...

2021-01-25 12:58 UTC, tamirkamara requested changes

2021-01-25 12:58 UTC, tamirkamara commented on .github/workflows/terraform-plan-apply-shared-rg.yml
> +    branches: [ '**' ]
you can delete this line to catch all branches.

2021-01-26 16:03 UTC, tamirkamara requested changes
It was decided that we'll use "main-latest" so need to update this PR.

2021-01-27 07:33 UTC, tamirkamara approved these changes

2021-01-27 12:55 UTC, anatbal approved these changes

2021-01-27 13:00 UTC, merged