init username,  pass and client id are passing into the init service
NDPH-ARTS/mts-trial-deployment-config pull request #60
Opened 2021-02-25 20:59 UTC by eladiw

## Description
init username,  pass and client id are passing into the init service

### Checklist:

- [ ] Branch name follows convention (feature/arts-###-short-name OR fix/arts-###-short-name)
- [ ] I have included a short-meaningful title, description and changes for this PR

2021-02-25 21:04 UTC, tamirkamara approved these changes, later dismissed

2021-02-25 21:04 UTC, LizaShak approved these changes, later dismissed

2021-03-01 16:21 UTC, tamirkamara requested changes

2021-03-01 16:21 UTC, tamirkamara commented on .github/workflows/terraform-plan-apply.yml
> +          terraform apply -var="init_username=${{secrets.INIT_USERNAME}}" -var="init_password=${{secrets.INIT_PASSWORD}}" -var="init_client_id=${{secrets.INIT_CLIENT_ID}}"  -auto-approve tfplan
No need to make any changes here. All vars pass in the plan output file.

2021-03-01 16:24 UTC, eladiw commented on .github/workflows/terraform-plan-apply.yml
> +          terraform apply -var="init_username=${{secrets.INIT_USERNAME}}" -var="init_password=${{secrets.INIT_PASSWORD}}" -var="init_client_id=${{secrets.INIT_CLIENT_ID}}"  -auto-approve tfplan
```suggestion
          terraform apply -auto-approve tfplan
```

2021-03-01 16:28 UTC, tamirkamara approved these changes

2021-03-02 06:56 UTC, LizaShak approved these changes

2021-03-02 07:16 UTC, merged