ARTS 355 - Limit public/internet access to API services
NDPH-ARTS/mts-trial-deployment-config pull request #71
Opened 2021-03-07 13:54 UTC by eladiw

## Description
Limit public/internet access to API services.
ALL SQL, KV  and web apps (except gateway) are now inside a vnet and communicate using vnet integration + private endpoints.
the gateway has vnet integration for outbound connections and remains publicly available.

### Changes
- [ARTS- 355] - Limit public/internet access to API services.

### Checklist:

- [ ] Branch name follows convention (feature/arts-###-short-name OR fix/arts-###-short-name)
- [ ] I have included a short-meaningful title, description and changes for this PR

2021-03-08 11:31 UTC, tamirkamara requested changes

2021-03-08 11:31 UTC, tamirkamara commented on terraform/trial_rg/modules/privateendpoint/main.tf
>      name                 = "${var.application}privatednszonegroup"
can't this name be separated with "-"?

2021-03-08 11:31 UTC, tamirkamara commented on terraform/trial_rg/modules/privateendpoint/main.tf
>    records             = [data.azurerm_private_endpoint_connection.endpoint-connection.private_service_connection.0.private_ip_address]
Looking at the private dns zone, this looks odd - you have 2 A records: this one you create here, and another one with a "nicer" name that I guess is created automatically, both are pointing to the same IP address. I don't see you reference/use this one anywhere, why do we need it?
This comment is also valid for the sql server (which, btw, don't follow the same name pattern for this resource), but oddly not for the keyvault...

2021-03-08 11:31 UTC, tamirkamara commented on terraform/trial_rg/modules/genericservice/main.tf
> +  count            = var.no_private_endpoint == true ? 0 : 1
perhaps this should be switched around to say enable_private_endpoint ?

2021-03-08 11:31 UTC, tamirkamara commented on terraform/trial_rg/modules/privateendpoint/variables.tf
> +variable "subresource_name" {
Not about this specifically, but looks like some of the vars aren't used...

2021-03-08 12:06 UTC, mdp0 submitted a review, later dismissed

2021-03-09 07:45 UTC, eladiw commented on terraform/trial_rg/modules/privateendpoint/main.tf
>    records             = [data.azurerm_private_endpoint_connection.endpoint-connection.private_service_connection.0.private_ip_address]
fixed

2021-03-09 07:50 UTC, eladiw commented on terraform/trial_rg/modules/genericservice/main.tf
> +  count            = var.no_private_endpoint == true ? 0 : 1
fixed

2021-03-09 07:51 UTC, eladiw commented on terraform/trial_rg/modules/privateendpoint/variables.tf
> +variable "subresource_name" {
talked f2f. on the next PR, I will do some refactoring which will include fixing this item

2021-03-09 07:55 UTC, tamirkamara approved these changes

2021-03-09 08:02 UTC, mdp0 approved these changes

2021-03-09 08:21 UTC, merged